insert into students (name, surname) values ('Caitrin', 'Cawse');
insert into students (name, surname) values ('Drucill', 'Greggersen');
insert into students (name, surname) values ('Alvy', 'Mudd');
insert into students (name, surname) values ('Nicky', 'Chittim');
insert into students (name, surname) values ('Diane-marie', 'Pollicott');
insert into students (name, surname) values ('Sharl', 'Yegorovnin');
insert into students (name, surname) values ('Nona', 'Housiaux');
insert into students (name, surname) values ('Ginny', 'Gration');
insert into students (name, surname) values ('Palm', 'Arkill');
insert into students (name, surname) values ('Haskell', 'Elliott');
insert into students (name, surname) values ('Hansiain', 'Cabel');
insert into students (name, surname) values ('Sheela', 'Bockh');
insert into students (name, surname) values ('Thelma', 'Greason');
insert into students (name, surname) values ('Cammie', 'Tweddle');
insert into students (name, surname) values ('Elberta', 'Banat');
insert into students (name, surname) values ('Obidiah', 'Johnke');
insert into students (name, surname) values ('Butch', 'Freddi');
insert into students (name, surname) values ('Benny', 'Tender');
insert into students (name, surname) values ('Cristy', 'Eichmann');
insert into students (name, surname) values ('Bancroft', 'Kuhnwald');
insert into students (name, surname) values ('Alexa', 'Francklyn');
insert into students (name, surname) values ('Ardith', 'Dignall');
insert into students (name, surname) values ('Clyde', 'Harry');
insert into students (name, surname) values ('Rickie', 'Gavaghan');
insert into students (name, surname) values ('Teirtza', 'Domenc');
insert into students (name, surname) values ('Orel', 'Ilieve');
insert into students (name, surname) values ('Iorgo', 'Branca');
insert into students (name, surname) values ('Hyacinth', 'Colcomb');
insert into students (name, surname) values ('Stace', 'Hucklesby');
insert into students (name, surname) values ('Kalle', 'Jobbings');
insert into students (name, surname) values ('Simone', 'Daybell');
insert into students (name, surname) values ('Jelene', 'Canet');
insert into students (name, surname) values ('Fidelia', 'Hails');
insert into students (name, surname) values ('Darbie', 'Martyns');
insert into students (name, surname) values ('Izabel', 'Hentze');
insert into students (name, surname) values ('Yardley', 'Westpfel');
insert into students (name, surname) values ('Nonah', 'Neiland');
insert into students (name, surname) values ('Dominick', 'Halm');
insert into students (name, surname) values ('Melesa', 'Woolger');
insert into students (name, surname) values ('Doralynn', 'Rysom');

insert into subjects (name) values ('Mathematics');
insert into subjects (name) values ('Science');
insert into subjects (name) values ('History');
insert into subjects (name) values ('Geography');
insert into subjects (name) values ('English');
insert into subjects (name) values ('Art');
insert into subjects (name) values ('Physical Education');
insert into subjects (name) values ('Biology');
insert into subjects (name) values ('Chemistry');
insert into subjects (name) values ('Physics');
insert into subjects (name) values ('Economics');
insert into subjects (name) values ('Philosophy');
insert into subjects (name) values ('Psychology');
insert into subjects (name) values ('Computer Science');
insert into subjects (name) values ('Music');
insert into subjects (name) values ('Sociology');
insert into subjects (name) values ('Drama');
insert into subjects (name) values ('Statistics');
insert into subjects (name) values ('Environmental Science');
insert into subjects (name) values ('Politics');